name: Build And Test

env:
  TARGET_NAME: mo_yanxi.utility.test
  LLVM_VER: 22

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [
          windows-latest,
          ubuntu-latest
        ]
        toolchain: [ msvc, clang, gcc ]
        mode: [ debug, release ]
        include:
          - os: windows-latest
            toolchain: msvc
          - os: windows-latest
            toolchain: clang

          # 2. Linux: 使用 GCC/Clang
#          - os: ubuntu-latest
#            toolchain: gcc
          - os: ubuntu-latest
            toolchain: clang

        exclude:
          - os: ubuntu-latest
            toolchain: msvc
          - os: windows-latest
            toolchain: gcc
    #          - os: ubuntu-latest
    #            toolchain: msvc
          - os: ubuntu-latest
            toolchain: gcc


    steps:
      - uses: actions/checkout@v4

      # 1. 设置 xmake 环境 (使用最新版)
      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest
      #          actions-cache-folder: '.xmake-cache'


      - name: Install LLVM  (Linux Clang only)
        if: matrix.os == 'ubuntu-latest' && matrix.toolchain == 'clang'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh ${{ env.LLVM_VER }}
          sudo apt-get install -y libc++-${{ env.LLVM_VER }}-dev libc++abi-${{ env.LLVM_VER }}-dev clang-tools-${{ env.LLVM_VER }} libunwind-${{ env.LLVM_VER }}-dev
          echo "/usr/lib/llvm-${{ env.LLVM_VER }}/bin" >> $GITHUB_PATH
          sudo update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
          sudo update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100
  
          clang --version

      - name: Build ${{ matrix.mode }}
        shell: bash
        run: |
          CONFIG_CMD="xmake f --mode=${{ matrix.mode }} --toolchain=${{ matrix.toolchain }} --add_test=y -y"
          
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            CONFIG_CMD="$CONFIG_CMD -p linux"
          else
            CONFIG_CMD="$CONFIG_CMD -p windows"
          fi
          
          # Linux Clang 特殊处理
          if [[ "${{ matrix.os }}" == "ubuntu-latest" && "${{ matrix.toolchain }}" == "clang" ]]; then
             # 动态获取安装路径，避免硬编码版本号带来的路径错误
             LLVM_PATH="/usr/lib/llvm-${{ env.LLVM_VER }}"
             EXTRA_FLAGS="--sdk=$LLVM_PATH --cxflags=-stdlib=libc++ --ldflags='-stdlib=libc++ -lc++abi -lunwind'"
          
             # 只有当安装了自定义 LLVM 时才导出 PATH
             echo "$LLVM_PATH/bin" >> $GITHUB_PATH
          
             CONFIG_CMD="$CONFIG_CMD $EXTRA_FLAGS"
          fi

          echo "Running: $CONFIG_CMD"
          eval $CONFIG_CMD

      - name: Test
        run: xmake run ${{ env.TARGET_NAME }}